title: Sam Spurlock
#email: samanthajoespurlock@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
  #Sam Spurlock, samanthajoespurlock@gmail.com
theme: jekyll-slender-template
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#github_username:  sspurlo2
#
